### ISSUE TITLE
Please update the build dependencies for Ubuntu 18.04 (add autoconf and libssl-dev)

### ISSUE THREAD

**Issue by liaoya** [asdf-community/asdf-php#12]
I have verified asdf-php installation on Ubuntu 18.04 cloud image. I think the following packages are required `autoconf bison build-essential curl gettext libcurl4-openssl-dev libedit-dev libicu-dev libjpeg-dev libmysqlclient-dev libpng-dev libpq-dev libssl-dev libxml2-dev libzip-dev openssl pkg-config zlib1g-dev`.
And `autoconf` and `libssl-dev` is missing in README.md

**Comment by imbsky** [comment]
Fixed in the latest master.
