### ISSUE TITLE
[MacOS] cURL issue on installing 5.6.40

### ISSUE THREAD

**Issue by abnersajr** [asdf-community/asdf-php#22]
Trying to install the PHP 5.6.40 this error are shown.
![image](https://user-images.githubusercontent.com/1998649/64079044-e506fd00-ccb8-11e9-8fb0-c3a33b952d65.png)

MacOS latest version. Mojave 10.14.6.
Curl was installed from Homebrew
Using ZSH. 
This is on my `.zshrc`
```sh
export PATH=/usr/local/opt/curl/bin:q$(brew --prefix openvpn):/sbin:$HOME/.asdf/shims:$HOME/bin:/usr/local/bin:$(brew --prefix bison@2.7)/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
```

**Comment by imbsky** [comment]
Same reason as https://github.com/asdf-community/asdf-php/issues/16.

**Comment by armaaar** [comment]
I have the same problem trying to install PHP 7.2.33. I've tried some solutions from https://github.com/phpbrew/phpbrew/issues/861 but since they are neither targeted for mac nor asdf it didn't work well with me.

@smorimoto This problem is not related with PHP version

**Comment by smorimoto** [comment]
Exec `whereis curl` to find the corresponding path and pass it directly. Does it still fail?

```
PHP_CONFIGURE_OPTIONS="--with-curl=/usr/include/curl" asdf install php <VERSION>
```

**Comment by smorimoto** [comment]
And did you check here? If you are using macOS, there are several steps you need to take.
https://github.com/asdf-community/asdf-php#prerequirements

**Comment by armaaar** [comment]
@smorimoto I've followed the workflow and read https://github.com/asdf-community/asdf-php/issues/61 with no luck. also I've tried defining curl path with `--with-curl` in `PHP_CONFIGURE_OPTIONS` but now it doesn't read `zlib` although it's installed and it had no problem reading it at first. I still need to do more tests...
