### ISSUE TITLE
Couldn't install on mac any version for PHP 7+

### ISSUE THREAD

**Issue by amadeu01** [asdf-community/asdf-php#23]
```
configure: error: Please reinstall libedit - I cannot find readline.h
```

![image](https://user-images.githubusercontent.com/11631092/64664577-f4f3af00-d425-11e9-8672-70409ee1e2d7.png)

**Comment by salzig** [comment]
Did you install libedit with `brew` (`brew install libedit`)? if not, maybe it helps. Else there is a mergerequest (#21) that adds detection for libedit

**Comment by imbsky** [comment]
See https://github.com/asdf-community/asdf-php/blob/master/.github/workflows/workflow.yml
