### ISSUE TITLE
New pkg-config flags for php 7.4

### ISSUE THREAD

**Issue by triptec** [asdf-community/asdf-php#28]
Docs here: [https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.pkg-config](https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.pkg-config)

I was not getting the zip extension so I changed --enable-zip to --with-zip in bin/install and it worked. I saw that there where other unrecognized flags that had to do with gd among others that probably needs changing.

**Comment by imbsky** [comment]
This should be fixed by #29.
