### ISSUE TITLE
Postgres pdo driver

### ISSUE THREAD

**Issue by gtkanal** [asdf-community/asdf-php#52]
Hi guys, I just want to know how can I install a php version with postgres driver if it really is possible.

Thanks

**Comment by imbsky** [comment]
It probably works by adding the `--with-pdo-pgsql` option [here](https://github.com/asdf-community/asdf-php/blob/master/bin/install#L71-L107), but I'm not familiar with PHP and don't know.

**Comment by imbsky** [comment]
or you can use it by setting the `--with-pdo-pgsql` option to the `PHP_CONFIGURE_OPTIONS` variable.

**Comment by gtkanal** [comment]
Nice, I put --with-pdo-pgsql on  bin/install, and it worked pretty well for me. 

I've tried `PHP_CONFIGURE_OPTIONS` as well, although it leads to some issues with https packages, I guess should be some config conflict in some point. 

many thanks for the tip ^^

**Comment by imbsky** [comment]
My pleasure.
