### ISSUE TITLE
What's the way to install pecl extensions ?

### ISSUE THREAD

**Issue by Atiladanvi** [asdf-community/asdf-php#60]
I have try modify the install script to add [redis](https://github.com/phpredis/phpredis) in php extension folder but i not have any idea if this is possible.

what do you suggest me ?

**Comment by imbsky** [comment]
I don't have time this month so I can't take a deep look at this, but I think we can do it easily without making any changes on the plugin side.

**Comment by imbsky** [comment]
This didn't work for you?

```bash
pecl install redis
```

**Comment by Atiladanvi** [comment]
> This didn't work for you?
> 
> ```shell
> pecl install redis
> ```

I try this:, but after i need activate redis.so after install. But the binaries php-fpm is compiled before

**Comment by j-dexx** [comment]
@Atiladanvi you can create a php.ini file in `~/.asdf/installs/php/php-version` that'll be picked up.

This works for me using xdebug installed with pecl.  I just add `zend_extension=path/to/xdebug.so` to a php.ini file.

**Comment by Atiladanvi** [comment]
@j-dexx Great ! This working for me. Before i tried activate this in php-fpm.conf. 
In some case is just add in php.ini `extension=redis.so`;.. php-fmp auto recognize de path `/Applications/MAMP/bin/php/phpX.Y.X/lib/php/extensions/no-debug-non-zts-xxxxxxxx`

**Comment by imbsky** [comment]
@j-dexx Thanks for your pointer :)

**Comment by j-dexx** [comment]
@imbsky Might be worth adding explicitly to the readme?

**Comment by imbsky** [comment]
Yeah, PR is always welcome 🙂
