### ISSUE TITLE
Unknown ./configure options

### ISSUE THREAD

**Issue by nate** [asdf-community/asdf-php#63]
I can't tell if this is an actual issue or not but I see this when installing php 7.4.7 on MacOS Catalina:

```
buildconf: Run ./configure to proceed with customizing the PHP build.
configure: WARNING: unrecognized options: --with-freetype-dir, --with-icu-dir, --with-jpeg-dir, --with-webp-dir, --with-png-dir, --with-libxml-dir, --with-libzip, --enable-gd-native-ttf, --enable-wddx, --enable-zip, --with-gd, --with-mysql
```

PHP installs fine and so far is working ok.

**Comment by imbsky** [comment]
If they do not exist, they are not set and the build will not fail. But, some configs may be missing.

**Comment by imbsky** [comment]
I don't have time to investigate this so if someone will investigate and create a PR if necessary, will review it.

**Comment by smorimoto** [comment]
Close this once, but if there is still a problem, please open it again.
