### ISSUE TITLE
Error command global not working

### ISSUE THREAD

**Issue by thevan96** [asdf-community/asdf-php#64]
- When set global, version error not install
![Screen Shot 2020-08-17 at 15 35 11](https://user-images.githubusercontent.com/47932916/90375499-3dd4ce80-e09f-11ea-9b6f-e6c3e8bb56a2.png)

**Comment by smorimoto** [comment]
Did you run install first?

**Comment by smorimoto** [comment]
```bash
asdf install php 7.3.21
asdf global php 7.3.21
php --version
```

**Comment by thevan96** [comment]
Thanks you.

**Comment by smorimoto** [comment]
Anytime 🙂
